services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000"
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
      mode: replicated
      resources:
        limits:
          cpus: '1'
          memory: 256M
    pull_policy: build
    networks:
      - internal
    environment:
      - NODE_ENV=production
    depends_on:
      - cache
  cache:
    image: valkey/valkey:8-alpine
    container_name: nestjs-api-cache
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 256M
    networks:
      - internal
  proxy:
    image: nginx:alpine
    container_name: nestjs-api-proxy
    restart: always
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 128M
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal

networks:
  internal:
