services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000"
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
      mode: replicated
      resources:
        limits:
          cpus: '1'
          memory: 96M
    pull_policy: build
    networks:
      - internal
    environment:
      - NODE_ENV=production
      - REDIS_HOST=cache
    depends_on:
      - cache
  cache:
    image: valkey/valkey:8-alpine
    container_name: nestjs-api-cache
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 64M
    networks:
      - internal
  proxy:
    image: nginx:alpine
    container_name: nestjs-api-proxy
    restart: always
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 32M
    ports:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal
      - nginx-pm_default

networks:
  internal:
  nginx-pm_default:
    external: true
