name: Tag on Merge

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      VERSION: 0.0.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          $VERSION=echo grep version package.json | awk '{print $2}' | cut -c2-6
          git tag -a v$VERSION -m "Release version v$VERSION"
          git push origin v$VERSION
