name: Tag on Merge

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      VERSION: 0.0.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create tag
        run: |
          grep version package.json | awk '{print $2}' | cut -c2-6 > $VERSION
          git tag -a v$VERSION -m "Release version v$VERSION"
          git push origin v$VERSION
